export const MOCK_MOVIES = {
  movies: [
    {
      id: 1,
      title: 'Matrix',
      description: 'Una película de ciencia ficción.',
      year: 1999,
      rate: 4.5,
      imagePath: './assets/movies/matrix.jpeg',
    },
    {
      id: 2,
      title: 'Titanic',
      description: 'Un drama romántico ambientado en un barco.',
      year: 1997,
      rate: 4.0,
      imagePath: './assets/movies/titanic.jpg',
    },
    {
      id: 3,
      title: 'Jurassic Park',
      description: 'Aventura con dinosaurios.',
      year: 1993,
      rate: 4.2,
      imagePath: './assets/movies/jurassic.jpg',
    },
    {
      id: 4,
      title: 'Star Wars: Episodio IV - Una Nueva Esperanza',
      description: 'Una galaxia muy, muy lejana.',
      year: 1977,
      rate: 4.7,
      imagePath: './assets/movies/star-wars.jpg',
    },
    {
      id: 5,
      title: 'Inception',
      description: 'Un thriller de ciencia ficción.',
      year: 2010,
      rate: 4.4,
      imagePath: './assets/movies/inception.jpg',
    },
    {
      id: 6,
      title: 'Pulp Fiction',
      description: 'Una película de crimen y drama.',
      year: 1994,
      rate: 4.6,
      imagePath: './assets/movies/pulp-fiction.jpg',
    },
    {
      id: 7,
      title: 'The Shawshank Redemption',
      description: 'Una película de drama y crimen en prisión.',
      year: 1994,
      rate: 4.7,
      imagePath: './assets/movies/shawshank-redemption.jpg',
    },
    {
      id: 8,
      title: 'The Godfather',
      description: 'Un clásico del crimen y el drama.',
      year: 1972,
      rate: 4.8,
      imagePath: './assets/movies/godfather.jpg',
    },
    {
      id: 9,
      title: 'Gladiator',
      description: 'Una película de acción y drama histórico.',
      year: 2000,
      rate: 4.4,
      imagePath: './assets/movies/gladiator.jpg',
    },
    {
      id: 10,
      title: 'The Dark Knight',
      description: 'Una película de superhéroes y crimen.',
      year: 2008,
      rate: 4.9,
      imagePath: './assets/movies/dark-knight.jpg',
    },
    {
      id: 11,
      title: 'Forrest Gump',
      description: 'Un drama sobre la vida de Forrest Gump.',
      year: 1994,
      rate: 4.5,
      imagePath: './assets/movies/forrest-gump.jpg',
    },
    {
      id: 12,
      title: 'Fight Club',
      description: 'Un drama psicológico y de acción.',
      year: 1999,
      rate: 4.6,
      imagePath: './assets/movies/fight-club.jpg',
    },
    {
      id: 13,
      title: 'The Matrix Reloaded',
      description: 'La secuela de Matrix.',
      year: 2003,
      rate: 4.2,
      imagePath: './assets/movies/matrix-reloaded.jpg',
    },
    {
      id: 14,
      title: 'Inglourious Basterds',
      description:
        'Una película de guerra y drama dirigida por Quentin Tarantino.',
      year: 2009,
      rate: 4.4,
      imagePath: './assets/movies/inglourious-basterds.jpg',
    },
    {
      id: 15,
      title: 'Avatar',
      description:
        'Una película de ciencia ficción y aventuras en otro planeta.',
      year: 2009,
      rate: 4.3,
      imagePath: './assets/movies/avatar.jpg',
    },
  ],
};
